### ISSUE TITLE
pip-tools can't handle URLs as packages

### ISSUE THREAD

**Issue by jaraco** [yougov/yg.emanate#5]
To address #4, I'm trying to run the tests on a late Python 3 (3.7b5). Because it requires pyyaml, and because of yaml/pyyaml#126, I'm trying to add a workaround for that bug. But it seems pip-compile can't handle it:

```
yg.emanate master $ git diff
diff --git a/dev-requirements.in b/dev-requirements.in
index 1b9cc11..3510fb1 100644
--- a/dev-requirements.in
+++ b/dev-requirements.in
@@ -10,3 +10,6 @@ Sphinx

 pytest
 mock
+
+# workaround for yaml/pyyaml#126
+git+https://github.com/yaml/pyyaml@master#egg=pyyaml;python_version=="3.7"
diff --git a/setup.py b/setup.py
index 3f42056..a7a16d1 100644
--- a/setup.py
+++ b/setup.py
@@ -18,17 +18,17 @@ requirements = [
 ]

 setup(
-    name='emanate',
-    version='0.3.0',
+    name='yg.emanate',
+    version='0.4.0',
     description="Lightweight event system for Python",
     long_description=readme + '\n\n' + history,
     author="YouGov, plc",
     author_email='dev@yougov.com',
     url='https://github.com/yougov/emanate',
     packages=[
-        'emanate',
+        'yg.emanate',
     ],
-    package_dir={'emanate': 'emanate'},
+    namespace_packages=['yg'],
     include_package_data=True,
     install_requires=requirements,
     license="MIT license",
```

```
yg.emanate master $ rwt pip-tools -- -m piptools compile --output-file dev-requirements.txt dev-requirements.in
Collecting pip-tools
  Using cached https://files.pythonhosted.org/packages/4c/69/4f33fea6c50ff873b7905abc404d8c26aab2accf8c099d67a35aebc09871/pip_tools-2.0.2-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/71/12/1b24a85f543658804027de982f7e5cb80543ea33ec396c887c099c75274c/first-2.0.1-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Installing collected packages: first, six, click, pip-tools
yg-emanate 0.4.0 requires blinker, which is not installed.
yg-emanate 0.4.0 requires pika, which is not installed.
yg-emanate 0.4.0 requires PikaChewie>=1.3, which is not installed.
Successfully installed click-6.7 first-2.0.1 pip-tools-2.0.2 six-1.11.0
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/piptools/__main__.py", line 16, in <module>
    cli()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/piptools/scripts/compile.py", line 182, in cli
    Resolver.check_constraints(constraints)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-ki3c5gx0/piptools/resolver.py", line 126, in check_constraints
    raise UnsupportedConstraint(msg, constraint)
piptools.exceptions.UnsupportedConstraint: pip-compile does not support URLs as packages, unless they are editable. Perhaps add -e option? (constraint was: pyyaml; python_version == "3.7" from git+https://github.com/yaml/pyyaml@master#egg=pyyaml;python_version=="3.7" (from -r dev-requirements.in (line 15)))
```

**Comment by lbolla** [comment]
Have you tried using the '-e' flag with the git url? I normally use urls as packages with pip-tools and it works fine.

**Comment by jaraco** [comment]
I get a different error trying to use `-e`.

```
diff --git a/dev-requirements.in b/dev-requirements.in
index 1b9cc11..49ed7a5 100644
--- a/dev-requirements.in
+++ b/dev-requirements.in
@@ -10,3 +10,6 @@ Sphinx

 pytest
 mock
+
+# workaround for yaml/pyyaml#126
+-e git+https://github.com/yaml/pyyaml@master#egg=pyyaml;python_version=="3.7"
yg.emanate master $ rwt pip-tools -- -m piptools compile --output-file dev-requirements.txt dev-requirements.in
Collecting pip-tools
  Using cached https://files.pythonhosted.org/packages/4c/69/4f33fea6c50ff873b7905abc404d8c26aab2accf8c099d67a35aebc09871/pip_tools-2.0.2-py2.py3-none-any.whl
Collecting six (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting first (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/71/12/1b24a85f543658804027de982f7e5cb80543ea33ec396c887c099c75274c/first-2.0.1-py2.py3-none-any.whl
Collecting click>=6 (from pip-tools)
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Installing collected packages: six, first, click, pip-tools
yg-emanate 0.4.0 requires blinker, which is not installed.
yg-emanate 0.4.0 requires pika, which is not installed.
yg-emanate 0.4.0 requires PikaChewie>=1.3, which is not installed.
Successfully installed click-6.7 first-2.0.1 pip-tools-2.0.2 six-1.11.0
Traceback (most recent call last):
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "';python_'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/__main__.py", line 16, in <module>
    cli()
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/scripts/compile.py", line 175, in cli
    src_file, finder=repository.finder, session=repository.session, options=pip_options))
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_file.py", line 93, in parse_requirements
    for req in req_iter:
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_file.py", line 168, in process_line
    wheel_cache=wheel_cache
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_install.py", line 156, in from_editable
    wheel_cache=wheel_cache)
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_install.py", line 91, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip.exceptions.InstallationError: Invalid requirement: 'pyyaml;python_version==3.7'
Traceback (most recent call last):
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/packaging/requirements.py", line 92, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1617, in parseString
    raise exc
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1607, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 3376, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/pyparsing.py", line 3164, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 6), (line:1, col:7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/req/req_install.py", line 82, in __init__
    req = Requirement(req)
  File "/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/rwt-4gdi5a78/piptools/_vendored/pip/_vendor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "';python_'"
```
